apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: testrail-config
  name: testrail-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
