apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: testrail-mysql
  name: testrail-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
