apiVersion: v1
kind: Service
metadata:
  labels:
    service: srv
  name: svc-srv
spec:
  ports:
    - name: svc-srv
      port: {{ .Values.srv.servicePort }}
      targetPort: 80
  selector:
    service: srv